version: '3'
services:
  db:
    container_name: sample-db
    image: mysql
    restart: always
    platform: linux/x86_64
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
